### ISSUE TITLE
Delivery club. Страница оформления заказа. Невозможно сменить способ оплаты.

### ISSUE THREAD

**Issue by Natali-Skv** [VK-BMSTU-QA/homework-2#17]
**Проект:** [https://tavide.xyz](https://tavide.xyz) 
**Приоритет:** major  
**Браузер:** Google Chrome Version 105.0.5195.125 (Official Build) (64-bit)

## Шаги воспроизведения
1. авторизоваться
2. положить одно или несколько блюд какого-либо ресторана в корзину
3. нажав кнопку "Заказать" внизу корзины, перейти на страницу оформления заказа /ordering  

## Ожидаемый результат
Можно сменить способ оплаты на  "Google Pay", "Sber Pay". Кнопки "Google Pay", "Sber Pay" активны.  
## Полученный результат
Невозможно сменить способ оплаты, кнопки "Google Pay", "Sber Pay" неактивны. При наведении на них некорректно отображается курсор (режим text)   

![pay_way1](https://user-images.githubusercontent.com/71991158/194714418-7dd49d3e-45ed-48f3-a5f5-85f270028a99.png)

**Comment by kirill555101** [comment]
аппрув

**Comment by Natali-Skv** [comment]
approved

**Comment by Andrey123815** [comment]
approved

**Comment by yutfut** [comment]
approved

**Comment by alexey-ershkov** [comment]
аппрув
