### ISSUE TITLE
Delivery club. Страница оформления заказа. Платная доставка при заказе на минимальную стоимость для бесплатной доставки

### ISSUE THREAD

**Issue by Natali-Skv** [VK-BMSTU-QA/homework-2#18]
**Проект:** [https://tavide.xyz](https://tavide.xyz) 
**Приоритет:** critical  
**Браузер:** Google Chrome Version 105.0.5195.125 (Official Build) (64-bit)

## Шаги воспроизведения
1. авторизоваться
2. перейти на страницу ресторана "Black Star Burger "[https://tavide.xyz/dishes/black-star-burger](https://tavide.xyz/dishes/black-star-burger) 
3. положить 8 штук "Соус сырный" (id=3343) в корзину
4. нажав кнопку "Заказать" внизу корзины, перейти на страницу оформления заказа */ordering* 

## Ожидаемый результат
Так как итоговая сумма 8 * 50Р = 400Р равна минимальной стоимости для бесплатной доставки в  "Black Star Burger" , то цена доставки должная быть равна 0Р. 
То есть на странице должно отображаться:
- Доставка 0Р
- Сообщение "Ваш заказ будет доставлен бесплатно"
## Полученный результат
На странице отображается:
- Доставка 99Р
- Сообщение "закажите еще на 0Р для бесплатной доставки"   
   
![basket](https://user-images.githubusercontent.com/71991158/194715717-d52872e1-f935-4da8-81a9-fc7071e7bffe.png)

**Comment by kirill555101** [comment]
аппрув

**Comment by Natali-Skv** [comment]
approved

**Comment by Andrey123815** [comment]
approved

**Comment by Andrey123815** [comment]
approved

**Comment by yutfut** [comment]
approved

**Comment by alexey-ershkov** [comment]
аппрув
