### ISSUE TITLE
OverMail. Страница регистрации. Пустая белая страница.

### ISSUE THREAD

**Issue by kllmagn** [VK-BMSTU-QA/homework-2#19]
**Приоритет**: критичный
**Браузер**: Safari Версия 16.0 (17614.1.25.9.10, 17614)

### Шаги воспроизведения

Пользователь не имеет активной сессии.
1. Перейти на страницу входа (https://overmail.online/login)
2. Перейти на страницу регистрации, вручную изменив адресную строку на https://overmail.online/registration.

### Ожидаемый результат
Отображается страница регистрации с полями для заполнения и кнопкой для создания нового пользователя.
<img width="1512" alt="Снимок экрана 2022-10-16 в 13 34 47" src="https://user-images.githubusercontent.com/70798414/196030687-6d496194-a4f5-40e8-bd59-0afeacf5d498.png">

### Полученный результат
Отображается пустой белый экран.
<img width="1511" alt="Снимок экрана 2022-10-16 в 13 34 37" src="https://user-images.githubusercontent.com/70798414/196030658-820ceb07-1c0e-4a24-812d-cc8360c8efc8.png">

**Comment by Sitleman** [comment]
approve

**Comment by papazloynt** [comment]
approve

**Comment by sashanau** [comment]
approve
