### ISSUE TITLE
Movie-Space. Главная страница. Не работает воспроизведение сериала с главной страницы.

### ISSUE THREAD

**Issue by nezhibitskiy** [VK-BMSTU-QA/homework-2#2]
**Приоритет:** критический
**URL:** https://movie-space.ru/
**Версия браузера:** Google Chrome Версия 105.0.5195.125 (Официальная сборка), (arm64)

**Как воспроизвести:**
1. Авторизоваться и редиректом попасть на главную страницу
2. При помощи перезагрузки страницы поймать сериал в месте предложенного фильма/сериала 
3. Нажать на кнопку "Смотреть онлайн"
<img width="1512" alt="Снимок экрана 2022-09-23 в 10 43 00" src="https://user-images.githubusercontent.com/71338063/191913586-d4569465-e6e0-47cf-bfa9-ac8c744653c4.png">

**Ожидаемый результат:** откроется плеер с первой серией сериала
**Фактический результат:** происходит редирект на загрузку, но плеер не запускается

**Дополнительные сведения:**
Запрос к API за сведениями о главном фильме/сериале:

![Снимок экрана 2022-09-23 в 11 02 59](https://user-images.githubusercontent.com/71338063/191917031-85e809fd-24d0-46f6-8fb1-80864afedeeb.png)

Ответ на запрос: 

![Снимок экрана 2022-09-23 в 11 03 28](https://user-images.githubusercontent.com/71338063/191917089-a2accbf0-4dbf-4667-aeca-ee863b412836.png)

Ошибки, выводимые в консоль при нажатии на кнопку "Смотреть онлайн":

<img width="1512" alt="Снимок экрана 2022-09-23 в 11 11 46" src="https://user-images.githubusercontent.com/71338063/191918513-76da73bb-9cd3-4404-9dbd-882dd8b53845.png">

Запрос к API при нажатии на кнопку "Смотреть онлайн" у сериала:

<img width="822" alt="Снимок экрана 2022-09-23 в 11 14 51" src="https://user-images.githubusercontent.com/71338063/191918940-e485f06f-bdff-4be6-a802-564cad1c1884.png">

Запрос к API при нажатии на кнопку "Смотреть онлайн" у фильма: 

<img width="1312" alt="Снимок экрана 2022-09-23 в 11 14 17" src="https://user-images.githubusercontent.com/71338063/191919002-ae414a98-19e7-42e9-8ab6-b7d37ab4e22a.png">

**Comment by mistergahan** [comment]
У вас только один баг на весь проект? Не верю!
