### ISSUE TITLE
OverMail. Черновики. Не сохраняются вложения в черновиках.

### ISSUE THREAD

**Issue by Sitleman** [VK-BMSTU-QA/homework-2#20]
Приоритет: критичный
Браузер: Chrome (Версия 106.0.5249.119)

### Шаги воспроизведения

1. Перейти на overmail.online
2. Авторизоваться
3. Нажать на кнопку "Написать".
4. Заполнить форму и прикрепить вложение.
5. Нажать на кнопку "Входящие".
6. В открывшемся popup окне нажать кнопку "да".
7. Перейти в окно "Черновик" и открыть только что созданный черновик.

### Ожидаемый результат

* Черновик с заполненными полями "Кому", "Тема", "Сообщение" и прикрепленным файлом.
![image](https://user-images.githubusercontent.com/41092173/196031212-55983f8a-bb2d-4610-b147-427b28d055a2.png)

### Полученный результат

* Черновик с заполненными полями "Кому", "Тема", "Сообщение". Вложений нет.
![image](https://user-images.githubusercontent.com/41092173/196031254-7df48fc2-62be-4fa0-8249-76d95e2808c8.png)

**Comment by kllmagn** [comment]
аппрув

**Comment by Sitleman** [comment]
approve

**Comment by papazloynt** [comment]
approve

**Comment by sashanau** [comment]
approve

**Comment by mistergahan** [comment]
аппрув
