### ISSUE TITLE
OverMail. Хедер. Сбрасывается выбранная тема при перезагрузке страницы.

### ISSUE THREAD

**Issue by Sitleman** [VK-BMSTU-QA/homework-2#21]
Приоритет: критичный
Браузер: Chrome (Версия 106.0.5249.119)

### Шаги воспроизведения

1. Перейти на overmail.online
2. Авторизоваться
3. Нажать на кнопку выбора темы.
4. В открывшемся меню выбрать "розовую" тему.
5. Убедиться, что тема применилась.
6. Перезагрузить страницу в браузере.

### Ожидаемый результат

* Перезагрузилась страница с "розовой" темой.
![image](https://user-images.githubusercontent.com/41092173/196031005-5a445eb6-045c-4151-b9b3-7114fe5d4520.png)

### Полученный результат

* На перезагруженной странице тема сбросилась на тему по умолчанию ("голубую").
![image](https://user-images.githubusercontent.com/41092173/196031017-4b54c524-ad3f-462f-9fe3-afb801a6cefa.png)

**Comment by kllmagn** [comment]
аппрув

**Comment by papazloynt** [comment]
approve

**Comment by sashanau** [comment]
approve

**Comment by mistergahan** [comment]
аппрув
