### ISSUE TITLE
OverMail. Страница отправки письма. Не обрабатывается ошибка с бека при большом тексте в теме.

### ISSUE THREAD

**Issue by papazloynt** [VK-BMSTU-QA/homework-2#22]
**Приоритет:** средний
**URL:** https://overmail.online/send
**Браузер:** Google Chrome версии 106.0.5249.119

### Шаги воспроизведения
1. Авторизироваться на [Overflow](https://overmail.online/login)
2.  Перейти по URL
3. Заполнить адрес получателя письма
4. Заполнить поле темы количеством символов, большим чем 500

### Ожидаемый результат
Вывод ошибки на экране, о том, что количество символов в поле темы слишком большое
### Полученный результат
1. Ошибка не появляется, письмо не отправляется
2. В консоли разработчика, приходит ошибка с бек энда
![image](https://user-images.githubusercontent.com/41233824/196031028-6512c04f-ef84-4cd2-8cec-6aedfa88d36d.png)
![image](https://user-images.githubusercontent.com/41233824/196031041-d9b5ed66-43dd-430a-9d52-e57fb6f6a785.png)

**Comment by kllmagn** [comment]
аппрув

**Comment by Sitleman** [comment]
approve

**Comment by sashanau** [comment]
approve

**Comment by mistergahan** [comment]
аппрув
