### ISSUE TITLE
OverMail. Страница регистрации. Некорректный текст ошибки при вводе неправильного логина.

### ISSUE THREAD

**Issue by kllmagn** [VK-BMSTU-QA/homework-2#23]
**Приоритет**: средний
**Браузер**: Safari Версия 16.0 (17614.1.25.9.10, 17614)

### Шаги воспроизведения
Пользователь не имеет активной сессии.
1. Перейти на страницу регистрации (https://overmail.online/registration)
2. Неверно заполнить поле "Логин" (например, написать любое слово кириллицей), остальные поля заполнять необязательно
3. Нажать кнопку "Создать"

### Ожидаемый результат
Сообщение о некорректности введенного значения в поле "Логин" отображается полностью, нет проблем с версткой страницы.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/70798414/196031259-0faf6808-8785-4526-bc6d-2b69f94d1b9f.png">

### Полученный результат
Сообщение о некорректности введенного значения обрезается снизу и заезжает на наименование поля "Пароль", находящегося ниже.
<img width="336" alt="Снимок экрана 2022-10-16 в 13 46 41" src="https://user-images.githubusercontent.com/70798414/196031058-4056097f-34b4-4516-b657-d58231e73cff.png">

**Comment by Sitleman** [comment]
approve

**Comment by sashanau** [comment]
approve

**Comment by papazloynt** [comment]
approve

**Comment by mistergahan** [comment]
Название не описывает суть бага
изменить на "Некорректный текст ошибки при вводе неправильного логина"

**Comment by kllmagn** [comment]
исправлено

**Comment by mistergahan** [comment]
аппрув
