### ISSUE TITLE
OverMail. Страница просмотра письма. Прикрепленные файлы не прикрепляются повторно при ответе на письмо.

### ISSUE THREAD

**Issue by papazloynt** [VK-BMSTU-QA/homework-2#24]
**Приоритет:** выоский
**URL:** https://overmail.online/send
**Браузер:** Google Chrome версии 106.0.5249.119

### Шаги воспроизведения
1. Авторизироваться на [Overflow](https://overmail.online/login)
2.  Отправить самому себе письмо на почту с любым прикрепленным файлом 
3. Перейти на вкладку входящих писем
4. Открыть это полученное письмо
5. Нажать на кнопку ответить

### Ожидаемый результат
Произойдет переадресация на страниция отправки письма, с текстом из полученного письма и вложенными в него файлами.
### Полученный результат
Вложенные файлы не прикреплеяются 

Полученное письмо со вложенным файлом:
![image](https://user-images.githubusercontent.com/41233824/196031455-6f1d480c-df94-48de-8203-e9fb2c65bcc8.png)
Форма ответа на полученное писмо:
![image](https://user-images.githubusercontent.com/41233824/196031466-8a536a21-cf09-4177-b7db-a355ca81c6b3.png)

**Comment by kllmagn** [comment]
аппрув

**Comment by Sitleman** [comment]
approve

**Comment by sashanau** [comment]
approve

**Comment by mistergahan** [comment]
аппрув
