### ISSUE TITLE
OverMail. Страница профиля. Ломается изображение в профиле при загрузке фотографии с неподдерживаемым расширением.

### ISSUE THREAD

**Issue by sashanau** [VK-BMSTU-QA/homework-2#25]
Приоритет: критичный
Браузер: Safari Версия 16.0 (17614.1.25.9.10, 17614)

### Шаги воспроизведения

1. Авторизоваться.
2. Перейти по URL https://overmail.online/profile.
3. Нажать на аватар.
4. Вставить файл с расширением .docx.

### Ожидаемый результат

Поддерживаемые форматы .jpeg .png.
При вставке файла с иным расширением, происходит оповещение
об ошибке под инпутами с описанием поддерживаемых форматов.
Контент картинки не изменяется.

### Полученный результат

Оповещение об ошибке не происходит.
Контент картинки меняется на иконку
![alt text](https://i.ibb.co/K9X43xm/2022-10-09-16-21-48.png)

**Comment by Sitleman** [comment]
approve

**Comment by kllmagn** [comment]
аппрув

**Comment by papazloynt** [comment]
approve

**Comment by mistergahan** [comment]
Описание не информативное

**Comment by mistergahan** [comment]
на что + картинка

**Comment by mistergahan** [comment]
аппрув
