### ISSUE TITLE
Delivery club. Страница оформления заказа. Кнопка "вернуться назад" браузера открывает корзину, вместо редиректа на страницу ресторана

### ISSUE THREAD

**Issue by Natali-Skv** [VK-BMSTU-QA/homework-2#27]
**Проект:** [https://tavide.xyz](https://tavide.xyz) 
**Приоритет:** minor  
**Браузер:** Google Chrome Version 105.0.5195.125 (Official Build) (64-bit)

## Шаги воспроизведения
1. авторизоваться
2. перейти на страницу любого ресторана, например "Black Star Burger" [https://tavide.xyz/dishes/black-star-burger](https://tavide.xyz/dishes/black-star-burger) 
3. положить одно или несколько блюд в корзину
4. нажав кнопку "Заказать" внизу корзины, перейти на страницу оформления заказа */ordering* 
5. нажать 1 раз кнопку навигации в браузере  :arrow_left: "вернуться назад"  

## Ожидаемый результат
Редирект на страницу ресторана, в котором оформляли заказ с сохранением блюд в корзине (например, [https://tavide.xyz/dishes/black-star-burger](https://tavide.xyz/dishes/black-star-burger)) . 
## Полученный результат
В адресной строке отображается *"/shoppingCart"*, сбоку отрисовалась корзина с блюдами.  

![navigation_shopping_cart](https://user-images.githubusercontent.com/71991158/196295276-ea0d2043-68b5-4321-9969-7db0309ee2cf.png)

Если повторно нажать на кнопку навигации в браузере  :arrow_left:, происходит ожидаемый редирект на страницу ресторана, в котором оформляли заказ с сохранением блюд в корзине (например, [https://tavide.xyz/dishes/black-star-burger](https://tavide.xyz/dishes/black-star-burger)) .

**Comment by kirill555101** [comment]
аппрув

**Comment by Andrey123815** [comment]
аппрув

**Comment by Natali-Skv** [comment]
аппрув

**Comment by yutfut** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
аппрув
