### ISSUE TITLE
Delivery club. Страница оформления заказа. При переходе с пустой корзиной на страницу оформления заказа через адресную строку отображается пустая страница

### ISSUE THREAD

**Issue by Natali-Skv** [VK-BMSTU-QA/homework-2#29]
**Проект:** [https://tavide.xyz](https://tavide.xyz) 
**Приоритет:** low  
**Браузер:** Google Chrome Version 105.0.5195.125 (Official Build) (64-bit)

## Шаги воспроизведения
1. если Ваша корзина не пуста -- очистить её, уменьшив количество блюд до 0 с помощью кнопок ":heavy_minus_sign:" на карточке блюда в корзине  
2. вставив в адресную строку "https://tavide.xyz/ordering", перейти на страницу оформления заказа

## Ожидаемый результат
На странице оформления заказа отображаются 
> - кнопка "заказать" неактивна
> - вместо корзины отображается надпись *"Чтобы сделать заказ, положите блюда в корзину"*
> - промокод (если применен, отображается название, если не применен, то ничего не отображается)
> - адрес доставки (тот, что был указан у пользователя перед переходом на страницу оформления заказа)
> - телефон пользователя (тот, на который зарегистрирован аккаунт пользователя)    
> - общая стоимость 0Р
> - цена доставки 0Р
> - суммарная скидка  0Р
> 
## Полученный результат
Страница оформления заказа абсолютно пустая   
   
![empty](https://user-images.githubusercontent.com/71991158/196302950-5cf9ca1d-cd6e-4e05-9c6f-896723937314.png)

**Comment by kirill555101** [comment]
аппрув

**Comment by Andrey123815** [comment]
аппрув

**Comment by Natali-Skv** [comment]
аппрув

**Comment by yutfut** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
аппрув
