### ISSUE TITLE
Delivery club. Страница оформления заказа.  Платная доставка становится бесплатной при переходе на страницу через адресную строку или с помощью кнопки "вперед" навигации браузера

### ISSUE THREAD

**Issue by Natali-Skv** [VK-BMSTU-QA/homework-2#30]
**Проект:** [https://tavide.xyz](https://tavide.xyz) 
**Приоритет:** critical  
**Браузер:** Google Chrome Version 105.0.5195.125 (Official Build) (64-bit)

## Шаги воспроизведения (вариант через адресную строку)
1. авторизоваться
2. перейти на страницу ресторана "Black Star Burger" [https://tavide.xyz/dishes/black-star-burger](https://tavide.xyz/dishes/black-star-burger) 
3. положить 1 штуку "Соус сырный" (id=3343) в корзину 
4. вставив в адресную строку "https://tavide.xyz/ordering", перейти на страницу оформления заказа   

## Шаги воспроизведения (вариант через кнопку навигации браузера "вперед")
1. авторизоваться
2. перейти на страницу ресторана "Black Star Burger" [https://tavide.xyz/dishes/black-star-burger](https://tavide.xyz/dishes/black-star-burger) 
3. положить 1 штуку "Соус сырный" (id=3343) в корзину 
4. нажав кнопку "Заказать" внизу корзины, перейти на страницу оформления заказа */ordering* 
5. нажав 2 раза кнопку навигации в браузере  :arrow_left: "назад", вернуться на страницу ресторана, например  "Black Star Burger" [https://tavide.xyz/dishes/black-star-burger](https://tavide.xyz/dishes/black-star-burger)    
6. нажав 2 раза кнопку навигации в браузере  :arrow_right: "вперед", вернуться на страницу оформления заказа */ordering* 

## Ожидаемый результат
На странице отображается, что:   
 - корзина пользователя содержит 1 штуку "Соус сырный" (id=3343) за 50Р
 - цена доставки = 99Р, так как 50Р < минимальной стоимости для бесплатной доставки в "Black Star Burger" (400Р)
 - итоговая стоимость заказа = 149Р
 
**страница */ordering*, на которую пользователь перещел через кнопку "заказать" внизу корзины (верная информация о стоимости, ожидаемый результат)**  
![reload_page](https://user-images.githubusercontent.com/71991158/196299325-071c21fd-5e63-47af-9508-3b59e6c28e97.png)

## Полученный результат
На странице отображается, что:   
 - корзина пользователя содержит 1 штуку "Соус сырный" (id=3343) за 50Р
 - цена доставки = 0Р
 - итоговая стоимость заказа = 50Р

**страница */ordering*, на которую пользователь перешел через адресную строку или через кнопку навигации браузера "вперед" (неверная информация о стоимости, полученный результат)** 
![reload_page_before](https://user-images.githubusercontent.com/71991158/196299446-1304aef8-7fe6-4c4e-bc39-bd9782fab1f7.png)

**Comment by kirill555101** [comment]
аппрув

**Comment by Andrey123815** [comment]
аппрув

**Comment by Natali-Skv** [comment]
аппрув

**Comment by yutfut** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
аппрув
