### ISSUE TITLE
Movie-Space. Страница профиля пользователя. Не переходит на страницу авторизации при выходе из аккаунта.

### ISSUE THREAD

**Issue by nezhibitskiy** [VK-BMSTU-QA/homework-2#31]
Приоритет: высокий

URL: https://movie-space.ru/profile
Версия браузера: Google Chrome Версия 105.0.5195.125 (Официальная сборка), (arm64)

Как воспроизвести:

  1. Авторизоваться
  2. Зайти в свой профиль
  3. Нажать на кнопку выхода из профиля

**Ожидаемый результат:** произойдет выход из аккаунта и будет совершен редирект на страницу авторизации
**Фактический результат:** происходит выход с аккаунта, но не происходит смена страницы на страницу с авторизацией (только после перезагрузки страницы)

**Comment by mistergahan** [comment]
Формат описания не соответствует требованиям, смотри у коллег

**Comment by mistergahan** [comment]
аппрув

**Comment by Betchika99** [comment]
разобраться с приоритетом
