### ISSUE TITLE
Movie-Space. Страница авторизации и регистрации. Происходит повторная загрузка элементов страницы, из-за чего они "дергаются".

### ISSUE THREAD

**Issue by nezhibitskiy** [VK-BMSTU-QA/homework-2#32]
Приоритет: средний
URL: https://movie-space.ru/login
Версия браузера: Google Chrome Версия 105.0.5195.125 (Официальная сборка), (arm64)

Как воспроизвести:

  1. Зайти на страницу авторизации 
  2.  Переключиться на страницу загрузки

**Ожидаемый результат:** Все элементы на странице останутся неподвижны за исключением смены формы авторизации на форму регистрации
**Фактический результат:** Логотип и прочие элементы перезагружаются, исчезая на мгновение и появляясь снова

На скриншоте загрузки сети видно, что сначала загрузились все элементы при первом запросе, после, через некоторый промежуток времени, когда поступил новый запрос, те же файлы снова скачиваются

![Снимок экрана от 2022-10-18 20-26-17](https://user-images.githubusercontent.com/71338063/196502147-bec493e4-03a9-4825-9a0e-db6af850d78e.png)

**Comment by mistergahan** [comment]
Формат описания не соответствует требованиям, смотри у коллег

**Comment by mistergahan** [comment]
аппрув
