### ISSUE TITLE
Movie-Space. Любая страница с фильмами. Последние фильмы в списке располагаются на разных краях страницы.

### ISSUE THREAD

**Issue by nezhibitskiy** [VK-BMSTU-QA/homework-2#33]
Приоритет: высокий
URL: https://movie-space.ru/
Версия браузера: Google Chrome Версия 105.0.5195.125 (Официальная сборка), (arm64)

Как воспроизвести:

  1. Авторизоваться и зайти на страницу сериала
  2. Пролистать страницу в конец

**Ожидаемый результат:** В случае не заполнения последней строки в списке фильмов, последние фильмы должны быть расположены по левому краю страницы.
**Фактический результат:** Последние фильмы расположены по ширине страницы.

![Снимок экрана от 2022-10-18 20-34-06](https://user-images.githubusercontent.com/71338063/196503646-9878ba46-972b-40a8-9de4-bc9b2528cfb2.png)
![Снимок экрана от 2022-10-18 20-38-21](https://user-images.githubusercontent.com/71338063/196504553-03b5ba6a-42c8-4f68-84c3-0dbdd9372546.png)

**Comment by mistergahan** [comment]
формат описания не соответствует требованиям, смотри у коллег
