### ISSUE TITLE
Movie-Space. Страница Избранное. При удалении всех элементов из избранного заголовок "Избранное" не перемещается и не появляется текст "Ваш каталог пустой"

### ISSUE THREAD

**Issue by vorolga** [VK-BMSTU-QA/homework-2#35]
**Приоритет:** высокий
**URL:** https://movie-space.ru/
**Версия браузера:** Google Chrome Version 105.0.5195.125 (Official Build) (arm64)

**Как воспроизвести:**

1. Авторизоваться и редиректом попасть на главную страницу <img width="1440" alt="Screenshot 2022-10-18 at 22 42 59" src="https://user-images.githubusercontent.com/72464470/196528450-95a7c59b-a4ae-40dd-a9c2-65ab2e90582a.png">
2. Добавить фильм или сериал в избранное
<img width="1440" alt="Screenshot 2022-10-18 at 22 56 59" src="https://user-images.githubusercontent.com/72464470/196531180-ca3f2270-81db-43b9-b0d6-9fd9542639b6.png">
3. Перейти на вкладку "Избранное" и удалить выбранный фильм или сериал
<img width="1440" alt="Screenshot 2022-10-18 at 22 58 03" src="https://user-images.githubusercontent.com/72464470/196531373-7316e70c-7aef-4083-b2d1-f0b6becd82ae.png">
<img width="1440" alt="Screenshot 2022-10-18 at 22 58 15" src="https://user-images.githubusercontent.com/72464470/196531411-750a2ae0-9842-4a3c-966d-755cbb0af360.png">
4. Перезагрузить страницу
<img width="1440" alt="Screenshot 2022-10-18 at 22 58 51" src="https://user-images.githubusercontent.com/72464470/196531529-33e7917d-310e-45a7-b37a-450e1dba5c43.png">

**Ожидаемый результат:** заголовок "Избранное" перемещается и под ним появляется текст "Ваш каталог пустой"
**Фактический результат:** заголовок "Избранное" остается на месте и не появляется текст "Ваш каталог пустой", это происходит только после перезагрузки страницы

**Comment by mistergahan** [comment]
аппрув
