### ISSUE TITLE
Movie-Space. Страница Фильма/Сериала. При обновлении страницы цвет рейтинга фильма/сериала всегда зелёный

### ISSUE THREAD

**Issue by iiivan-lemon** [VK-BMSTU-QA/homework-2#36]
**Приоритет:** высокий
**URL:** https://movie-space.ru/
**Версия браузера:** Google Chrome Version 105.0.5195.125 (Official Build) (arm64)

**Как воспроизвести:**

1. Авторизоваться и редиректом попасть на главную страницу
2. Выбрать любой фильм/сериал и перейти на его страницу

![image](https://user-images.githubusercontent.com/74594938/196536212-16ba10c8-ddb5-44c5-8f6d-412691f89c39.png)
![image](https://user-images.githubusercontent.com/74594938/196536337-eb22ea00-256b-4fa3-b627-6dc25f6e06a7.png)

3. Выставить рейтинг отличный от 7-10 ( жёлтого и красного цвета )
![image](https://user-images.githubusercontent.com/74594938/196536911-19934f1c-e135-4be3-bbd2-27940266f434.png)
![image](https://user-images.githubusercontent.com/74594938/196537362-33156965-d047-4357-8c33-c6916b5774d4.png)
4. Перезагрузить страницу
![image](https://user-images.githubusercontent.com/74594938/196537619-0e2b9b78-1b42-4487-96f3-c5091d032044.png)
![image](https://user-images.githubusercontent.com/74594938/196537494-8bc85c6c-6619-4c14-b9ca-68cdf548d68f.png)

**Ожидаемый результат:** цифра рейтинга от 1 до 3 красного цвета, цифра рейтинга от 4 до 6 жёлтого цвета 
**Фактический результат:** цифра рейтинга от 1 до 6 зеленого цвета

**Comment by mistergahan** [comment]
Все ок

**Comment by Betchika99** [comment]
Добавить про дизайн инфо, чтобы оправдать приоритет
