### ISSUE TITLE
Movie-Space. Страница Избранное. При удалении всех сериалов из избранного заголовок и карточки фильмов съежают

### ISSUE THREAD

**Issue by iiivan-lemon** [VK-BMSTU-QA/homework-2#37]
**Приоритет:** высокий
**URL:** https://movie-space.ru/
**Версия браузера:** Google Chrome Version 105.0.5195.125 (Official Build) (arm64)

Как воспроизвести:

1. Авторизоваться и редиректом попасть на главную страницу Screenshot 2022-10-18 at 22 42 59
2. Добавить фильм и сериал в избранное
![image](https://user-images.githubusercontent.com/74594938/196540978-ec522997-1f23-490f-a0af-6668499a4b4d.png)
![image](https://user-images.githubusercontent.com/74594938/196541079-db0f5710-a274-4456-bb37-361796c12869.png)

3. Перейти на вкладку "Избранное" и удалить все сериалы
![image](https://user-images.githubusercontent.com/74594938/196542079-21376cfd-b743-471b-8693-796473e00333.png)
![image](https://user-images.githubusercontent.com/74594938/196541598-04fee163-af31-461a-b1de-481efda78599.png)

**Ожидаемый результат:** карточки фильмов и заголовок остаются в прежнем положении
**Фактический результат:** карточки фильмов и заголовок съезжают наверх

**Comment by mistergahan** [comment]
Есть фото в описании шагов, но нет фото в "Фактический результат"

**Comment by Betchika99** [comment]
Подобрать более корректный пример для воспроизведения бага, убрать скрины из шагов, добавить скрины для результатов

**Comment by Betchika99** [comment]
Разобраться с приоритетом
